name       : vivaldi-snapshot
version    : 3.5.2080.3
release    : 261
source     :
    - https://downloads.vivaldi.com/snapshot/vivaldi-snapshot_3.5.2080.3-1_amd64.deb : c1230973bd9285ff5f4ac0c8bcf933f36b1ae6a4c6d324c311b8a606054efb34
license    : Distributable
component  : network.web.browser
summary    : Vivaldi Web Browser (Snapshot)
description: |
    An advanced browser made with the power user in mind.
strip      : no
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - ffmpeg-chromium
rundeps    :
    - ffmpeg-chromium
setup      : |
    ar xf $sources/vivaldi-snapshot_${version}-1_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    # This only excludes /usr/bin link which will be invalid
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    cp -R root/usr/share/{applications,menu} $installdir/usr/share/

    # We do not use /opt for binary packages in Solus, so just use /usr/share.
    cp -R root/opt/* $installdir/usr/share/.
    ln -sv /usr/share/vivaldi-snapshot/vivaldi-snapshot $installdir/usr/bin/vivaldi-snapshot

    # Ensure we symlink to expected directory as expected file.
    # See https://gist.github.com/ruario/55a6671b155fe1da35a8d8a5b2352008
    majMin=$(echo '%version%' | cut -c-3)
    ln -s /usr/lib64/libffmpeg.so $installdir/usr/share/vivaldi-snapshot/libffmpeg.so.${majMin}

    for icon_size in 16 22 24 32 48 64 128 256; do
        install -D -m 00644 root/opt/vivaldi-snapshot/product_logo_${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/vivaldi-snapshot.png
    done
