name       : vivaldi-snapshot
version    : 2.9.1705.30
release    : 217
source     :
    - https://downloads.vivaldi.com/snapshot/vivaldi-snapshot_2.9.1705.30-1_amd64.deb : 086fa75ee52005b703130ee9abb6cf56084a9f3e41eed475fdb781562672c2d3
license    : Distributable
component  : network.web.browser
summary    : Vivaldi Web Browser (Snapshot)
description: |
    An advanced browser made with the power user in mind.
strip      : no
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - ffmpeg-chromium
setup      : |
    ar xf $sources/vivaldi-snapshot_${version}-1_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    # This only excludes /usr/bin link which will be invalid
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    cp -R root/usr/share/{applications,menu} $installdir/usr/share/

    # We do not use /opt for binary packages in Solus, so just use /usr/share.
    cp -R root/opt/* $installdir/usr/share/.
    ln -sv /usr/share/vivaldi-snapshot/vivaldi-snapshot $installdir/usr/bin/vivaldi-snapshot

    # Use system chromium ffmpeg
    rm $installdir/usr/share/vivaldi-snapshot/lib/libffmpeg.so
    # Removes a confusing warning message
    ln -s /usr/lib64/libffmpeg.so $installdir/usr/share/vivaldi-snapshot/

    for icon_size in 16 22 24 32 48 64 128 256; do
        install -D -m 00644 root/opt/vivaldi-snapshot/product_logo_${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/vivaldi-snapshot.png
    done
