name       : vivaldi-snapshot
version    : 1.5.658.31
release    : 42
source     :
    - https://downloads.vivaldi.com/snapshot/vivaldi-snapshot_1.5.658.31-1_amd64.deb : 319ec7d0fc9adc12e365ff87e77210eda54e1678e42491811c1e3376d995d188
license    : Distributable
component  : network.web.browser
summary    : Vivaldi Web Browser (Snapshot)
description: |
    An advanced browser made with the power user in mind.
strip      : no
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
setup      : |
    ar xf $sources/vivaldi-snapshot_${version}-1_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    # This only excludes /usr/bin link which will be invalid
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    cp -R root/usr/share/{applications,menu} $installdir/usr/share/

    # We do not use /opt for binary packages in Solus, so just use /usr/share.
    cp -R root/opt/* $installdir/usr/share/.
    ln -sv /usr/share/vivaldi-snapshot/vivaldi-snapshot $installdir/usr/bin/vivaldi-snapshot

    for icon_size in 16 22 24 32 48 64 128 256; do
        install -D -m 00644 root/opt/vivaldi-snapshot/product_logo_${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/vivaldi-snapshot.png
    done
